# Generated by Django 2.2.19 on 2021-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
